#!/bin/sh

if [ "$1" = "-h" ]; then
  echo Usage: $0 ISAMPLE NSKIP NEVT DBG
  exit 0
fi

ARG=1
if [ -n "$1" ]; then ARG=$1; fi
NSKIP=0
if [ -n "$2" ]; then NSKIP=$2; fi
NEVT=1
if [ -n "$3" ]; then NEVT=$3; fi
GDB=
if [ -n "$4" ]; then GDB=$2; fi

AFCL="-c LbTupler.fcl"
AFCL="-c run.fcl"

# Location for data files.
DATADIR=/lbne/app/users/dladams/data
if [ `hostname` = atlassw9.phy.bnl.gov ]; then
  DATADIR=/home/dladams/lbne/data
fi

if [ $ARG -eq 0 ]; then
  FILE="../prod/single35t_gen.root"
else if [ $ARG -eq 1 ]; then
  FILE="../prod/single35t_hits.root"
else if [ $ARG -eq 2 ]; then
  FILE=$DATADIR/AntiMuonCutEvents_LSU_lbne35t_31_20150220T200710_gen_20150220T205417_g4_20150220T210305_detsim_20150220T212153_reco.root
  FW_SEARCH_PATH=./gdml:$FW_SEARCH_PATH
else if [ $ARG -eq 3 ]; then
  FILE=$DATADIR/prodcosmics_lbne35t_milliblock_1_20150220T201346_gen_20150220T213621_g4_20150220T234543_detsim_milliblock_20150223T214501_reco_milliblock.root
  FW_SEARCH_PATH=./gdml:$FW_SEARCH_PATH
else if [ $ARG -eq 4 ]; then
  FILE="../prod/text_gen.root"
else if [ $ARG -eq 5 ]; then
  FILE="../prod/text_hits.root"
else if [ $ARG -eq 6 ]; then
  FILE=$DATADIR/prodgenie_numu_nc_uniform_flux_uboone_20150706T151726_gen_4e2e9fd3-96fd-42a1-8522-1e0a7c11b4cc.root
else if [ $ARG -eq 7 ]; then
  # MCC3 single muon
  FILE=$DATADIR/AntiMuonCutEvents_LSU_lbne35t_7_20150612T222627_gen_20150613T005121_g4_20150613T012324_detsim_20150613T015359_reco.root
else if [ $ARG -eq 8 ]; then
  # MCC3 milliblock
  FILE=$DATADIR/prodcosmics_lbne35t_milliblock_1_20150612T225517_gen_20150613T020241_g4_20150613T023146_detsim_milliblock_20150613T183059_reco_milliblock.root
fi; fi; fi; fi; fi; fi; fi; fi; fi

ARGS="-n $NEVT --nskip $NSKIP $AFCL $FILE"

if [ -n "$GDB" ]; then
  EXE=`which lar`
  echo $EXE --arg "$ARGS"
  #gdb $EXE --arg "$ARGS"
  echo "gdb --arg lar $ARGS"
  gdb --arg lar $ARGS
else
  lar $ARGS | tee run.log
fi
